apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: anagnole/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: anagnole/client
  context: client
  sync:
    manual:
      - src: '**/*.js'
        dest: .
  docker:
    dockerfile: Dockerfile
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-398918
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
